name: docs
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  MKDOCS_MATERIAL_VER: 9.1.4

jobs:
  publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t my-mkdocs-image \
            -f Dockerfile .
        env:
          DOCKER_BUILDKIT: 1

      - name: Deploy MkDocs Site
        run: |
          docker run -v $(pwd):/docs my-mkdocs-image gh-deploy --force --strict
